### ISSUE TITLE
Grayscale or RGB

### ISSUE THREAD

**Issue by mohammad-karam** [haverland/between_to_numbers#4]
It is not clear if I need to predict an image should it be Gray-scale or RGB photo? I think Grayscale would be enough but I still see models in RGB . Could you give a reason why should we we use RGB photo? 

Thanks!

**Comment by haverland** [comment]
Thanks for your comment.

On you question I've updated the Readme.md. Depending on the original project (https://github.com/jomjol/AI-on-the-edge-device) and it's history we using rgb at now for easier integration. The images comes from the esp32-edgeAI device. Here can the collecting application https://github.com/haverland/collectmeterdigits used.

The discussion of rgb or grayscale is an older one. Yes it is not really relevant for the recognition. Both have nearly the same accuracy. If we have rgb images, we can easily move to grayscale later on.
